name: Generate Snake Animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite a execução manual a qualquer momento
  workflow_dispatch:
  
  # Executa em cada push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Verifica o código do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Gera o SVG do jogo Snake com base nas contribuições do GitHub
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@v3
        with:
          github_user_name: DGuabiraba
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Verifica se os arquivos foram gerados
      - name: Check if files were generated
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "No files generated in dist/. Exiting..."
            exit 1
          fi

      # Commit e push dos SVGs gerados para a branch de saída
      - name: Commit and Push Files
        run: |
          git config --global user.name "DGuabiraba"
          git config --global user.email "daviguabiraba00@gmail.com"
          git checkout -b output
          git add dist/
          git commit -m "Generate snake animation"
          git push -u origin output --force
