name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Gerar snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: DGuabiraba
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

          config_file: .github/snk-config.yaml

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          commit_message: "snake animation update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
